### ISSUE TITLE
OpenAPI basics: what does "/" mean?

### ISSUE THREAD

**Issue by pebau** [opengeospatial/ogc_api_coverages#1]
If in a URL, say "http://....../..../a/b/c", what does "a/b" actually mean? Naturally, I would expect that "b is a sub-resource of a", but that does not always apply. Before we start building a whole framework on this we may want to clarify this.

**Comment by pebau** [comment]
Dear all,

my deep regrets, due to jetlag I totally forgot about the telecon. I'll duly
study any minutes available. Any next telecon around the corner?

-Peter



-- 
Dr. Peter Baumann
 - Executive Director, rasdaman GmbH Bremen (HRB 26793)
   www.rasdaman.com, mail: baumann@rasdaman.com
   tel: 0800-rasdaman, fax: 0800-rasdafax, mobile: +49-173-5837882
 - Professor of Computer Science, Jacobs University Bremen
   www.faculty.jacobs-university.de/pbaumann
   mail: p.baumann@jacobs-university.de
   tel: +49-421-200-3178, fax: +49-421-200-493178
"A brilliant idea is a job halfdone."

**Comment by Schpidi** [comment]
Hi @pebau, yes, as agreed we have weekly telecons at least until the hackathon.

**Comment by Schpidi** [comment]
20190412 WCS.SWG Telecon: The overall URI/IRI is hierarchical. We don't need this discussion right now and agree to close the issue (at least for now).
