### ISSUE TITLE
What extensions should OAPI Coverages have?

### ISSUE THREAD

**Issue by pebau** [opengeospatial/ogc_api_coverages#15]
In addition to the Core functionality, at some time a wider range of operations should be supported, such as further subsetting, scaling, etc. Here a first attempt:
* Range subsetting (also known as band subsetting, variable extraction)
* Scaling (change of grid resolution while keeping the space/time extent)
* CRS transformation (space, time, and possibly other dimension types!) +
* Transaction (insert, update, and deletion of coverages)
* Interpolation (whenever interpolation is involved in the request on hand, the method indicated shall be applied)
* Processing (WCPS queries for extraction, filtering, aggrgation, analytics, etc.)

Items marked with a "+" are of relevance beyond coverage world and might be discussed in a wider context.

**Comment by Schpidi** [comment]
Teleconference 20190426: How will this extend to application profiles?

**Comment by pebau** [comment]
WCS knows about 2 types of extensions:
* enhancing an existing request type, like GetCoverage, with further parameters to enhance and/or finetune behavior
* add new request types altogether (such as insert coverage)

**Comment by phersh2** [comment]
We'll have to figure out how all this applies to Application Profiles to WCS (MetOcean and EO), as well as the two type of extensions: 1) to GetCoverage and 2) extensions that include new extraction patterns (which includes the extension to the MetOcean Application Profile in the GetCorridor and GetPolygon functions)

**Comment by pebau** [comment]
we might also consider extensions for the various encodings, such as:
* XML, JSOB, RDF, ...
* GeoTIFF, NetCDF, GRIB2, ...
Note that standards exist for many formats, explaining how a coverage should be represented in that format.

**Comment by cmheazel** [comment]
The current version (12/30/19) has the following conformance classes:
 - core
 - subset
 - HTML
 - JSON
 - OAS30
There is also a discussion of content negotiation and requirements for the default mime-types. 
I have not included a conformance class for all possible formats due to the large number of possibilities.

**Comment by pebau** [comment]
FWIW, WCS is structured into format encodings, processing functionality, and protocol bindings.

**Comment by pebau** [comment]
Have created a branch extensions with some stub contents: https://github.com/opengeospatial/ogc_api_coverages/tree/extensions/extensions, hopefully helps in discussion.

**Comment by Schpidi** [comment]
In the WCS SWG Teleconference @cmheazel volunteered to make sure the core/extension structures like directories, Readme, etc. are aligned between common, features, and coverages.

**Comment by cmheazel** [comment]
OBE - the process for managing extensions has matured since this issue was written.
