### ISSUE TITLE
Req 1.4 unclear

### ISSUE THREAD

**Issue by pebau** [opengeospatial/ogc_api_coverages#16]
[Req 1.4](https://github.com/opengeospatial/ogc_api_coverages/blob/master/OAPI-Coverages/Requirements/requirements_class_common.adoc)  says: "A bounding box query SHALL return a list of all coverages from the specific collection that interescts the area bounded by that bounding box. "

Aside from the typo, it is not always a collection that is addressed, it can also be a single coverage, and then we want to do subsetting. 

Recommendation: explicitly state "A bounding box query on a collection...."

**Comment by Schpidi** [comment]
Teleconference 20190503: Distinction between filtering and subsetting. The `bbox` parameter is a simple entry to filtering. Extend filtering with more sophisticated `subset` parameters. Proposal to support both mechanisms for filtering.

**Comment by Schpidi** [comment]
This issue is not relevant anymore with the recent decision to use `/collections/{collectionid}/coverage` instead of `coverages` which makes filtering on this level obsolete.
