### ISSUE TITLE
Req 4.1 unclear

### ISSUE THREAD

**Issue by pebau** [opengeospatial/ogc_api_coverages#17]
[Req 4.1](https://github.com/opengeospatial/ogc_api_coverages/blob/master/OAPI-Coverages/Requirements/requirements_class_encoding.adoc) says: "If an encoding HTTP header (Accept and Accept-Encoding) is provided then a representation of the coverage in the format indicated SHALL be returned."

I believe what is intended is: "If an encoding HTTP header (Accept and Accept-Encoding) is provided in the request then a representation of the coverage in one of the formats indicated SHALL be returned."

**Comment by Schpidi** [comment]
Teleconference 20190503: This requirement may not need to be here at all. Content negotiation is likely inherited from common and HTTP 1.1.

**Comment by Schpidi** [comment]
This requirement isn't present anymore as it is inherited from OGC API - Common. The language in the README.md has been adjusted.
