### ISSUE TITLE
Do not enumerate coverage components

### ISSUE THREAD

**Issue by pebau** [opengeospatial/ogc_api_coverages#18]
[Req 2.3](https://github.com/opengeospatial/ogc_api_coverages/blob/master/OAPI-Coverages/Requirements/requirements_class_path.adoc) says: "A coverage accessed according to requirement 2.2 SHALL be returned as multipart coverage including the DomainSet, RangeType, and RangeSet in the coverage’s Native Format."

I would not enumerate components - a coverage is well defined, we just need to say that we return the complete coverage. Otherwise there is the danger of missing items - in this case: metadata, coverageFunction, etc.

**Comment by Schpidi** [comment]
Teleconference 20190503: Agreed
