### ISSUE TITLE
identifier syntax for OAPI Common

### ISSUE THREAD

**Issue by pebau** [opengeospatial/ogc_api_coverages#19]
in several places we use identifiers (such as coverages, collections). We should define admissible names and their representation, such as: char set, encoding, entities for escaping special characters, etc.

**Comment by Schpidi** [comment]
Teleconference 20190503: Likely a topic for OGC API Common or even OpenAPI. Use international IRIs (RFC 3987). Comply to RFC 6570 "URI Template".

**Comment by cmheazel** [comment]
The only real restriction I can think of is that path elements cannot include the ":" character. So qualified names cannot be used as commonly formatted <scope>:<name>. Unless we want to specify how to work around this limitation, then I think @Schpidi suggestion to specify compliance with RFC 3987 and 5670 are the best option.

**Comment by hylkevds** [comment]
For inspiration, OData (OGC SensorThings API) specifies for identifiers when used in URLs:

- numbers are put in as-is
- strings are quoted with single quotes (`'`) and single quotes in the string are doubled (`''`), essentially as Ansi SQL. Any character is valid, including slashes, backslashes, colons. Certain characters have to be URL encoded (Percent-encoding) as per the URL specification to ensure the resulting URL is valid.

**Comment by ghobona** [comment]
How about using the text below, taken from OGC API - Features"

"This document does not restrict the lexical space of URIs used in the API beyond the requirements of the HTTP and URI Syntax IETF RFCs. If URIs include reserved characters that are delimiters in the URI subcomponent, these have to be percent-encoded. See Clause 2 of RFC 3986 for details."

http://docs.opengeospatial.org/is/17-069r3/17-069r3.html#_http_uris

**Comment by hylkevds** [comment]
percent-encoding of slashes in the path-part of a URL is problematic. Tomcat simply doesn't allow it, many other systems have problems with it too. Essentially, the Features text ends up being "slashes are not allowed in identifiers", so it would be better to explicitly state that...

**Comment by Schpidi** [comment]
In the_ WCS SWG teleconference it was decided to recommend using hyphens to encode colons as used in qualified names to OGC NA and ask for feedback.

**Comment by ghobona** [comment]
Please note this comment https://github.com/opengeospatial/NamingAuthority/issues/55#issuecomment-643399279

**Comment by Schpidi** [comment]
20200708: As stated in https://github.com/opengeospatial/NamingAuthority/issues/55 this would be out of scope of OGC-NA and best addressed by OGC API standards themselves which would probably make it an OGC API - Common issue.

**Comment by cmheazel** [comment]
This issue has been re-assigned to API-Common [Issue 153](https://github.com/opengeospatial/oapi_common/issues/153).
