### ISSUE TITLE
Evaluate previous work for Coverages API

### ISSUE THREAD

**Issue by cmheazel** [opengeospatial/ogc_api_coverages#2]
D004 Swath Coverages (from TB-14)
WCS Core 2.1: 17-089r1
Coverages Implementation Schema: 09-146r6

**Comment by Schpidi** [comment]
Teleconference 20190426: captured resolution in [wiki page](wiki/Decisions)

**Comment by chris-little** [comment]
@Schpidi 
I get a RESTful 404 when I click on that link.
chris

**Comment by nmtoken** [comment]
more stressful than restful

**Comment by Schpidi** [comment]
sorry, the link should be to this [wiki page](/opengeospatial/ogc_api_coverages/wiki/Decisions)
