### ISSUE TITLE
Change coverages to coverage in the API

### ISSUE THREAD

**Issue by joanma747** [opengeospatial/ogc_api_coverages#28]
As a results of this discussions: 
* https://github.com/opengeospatial/WFS_FES/issues/249
* https://github.com/opengeospatial/ogc_api_coverages/issues/25

I became convinced that coverages needs to be replaced by "coverage" in the API.

/collecions/{collectionId}/coverage
(simetric to: /collecions/{collectionId}/items)

**Reason 1:**
Features are too atomic and need to be aggregated in collections for convenience: e.g. to cover a particular extent. Coverages are already an aggregation of data into a coverage structure: a boxel, a point cloud etc. They also have several "attributtes" represented by "rangeTypes" like features.

To me "coverage" is equivalent to "items". They both cover an extent, represent several attributes and can be queried. It is possible to move from items to a coverage by rasterization and for a coverage to items by vectorization. A point cloud can be transformed into a collection of points in a much more direct way.

**Reason 2:**
In OGC API coverages the collectionId becomes the coverage name in the same way that the collectionId is the _feature collection_ id in OGC API features. Both can be transformed into maps and tiles using:
/collecions/{collectionId}/map
without even knowing the collection type. It becomes symmetric.
They can also be processed in the OPC API processes without caring about the collection type.

Please note that the need for collections of collections is a completely different discussion that also affects features and should be solved in OGC API Common.

So I'm requesting to change the current orientation of the OGC API coverage to use _coverage_ (in singular) and use the {collectionId} and the name of the coverage.

So: 
/collecions/{collectionId}/coverage gets the whole coverage
/collecions/{collectionId}/coverage/rangeSet gets the actual values
/collecions/{collectionId}/coverage/domainSet gets the dimensions definition.

**Comment by Schpidi** [comment]
After quite some discussions at the OGC TC meetings in Banff on 20190909 and Toulouse on 20191120 the WCS.SWG agreed to adopt the resource path `/collections/{collectionId}/coverage` and drop the plural version.
In addition there is a proposal to have more concrete resource types like `rectifiedGridCoverage` in addition to `coverage` in the path.
