### ISSUE TITLE
Consider WCS Core service model

### ISSUE THREAD

**Issue by pebau** [opengeospatial/ogc_api_coverages#4]
WCS Core already contains a service model along which service facets can be modelled in an intuitive way; see Figure 1 in 09-110r4. Effectively, all current WCS Core operations can be nicely described a extracting this or that component(s) from the overall service model tree.

Advantage: request writers can intuitively construct what they want without learning lots of individual items by heart.

Attached a simplified version of WCS Core Fig 1.
![untitled2](https://user-images.githubusercontent.com/6102670/54693091-53e70400-4b26-11e9-8b16-3eb95d500d00.png)

**Comment by cmheazel** [comment]
@pebau The current version (12/30/19) identifies a Coverage Offering, but the associated schema is rather sparse. A link to service parameters could be added to this resource.

**Comment by Schpidi** [comment]
In the WCS SWG teleconference it was discussed that the current draft uses CIS extensively but that is inappropriate to rely on the WCS service model more than this. OAPI Coverages has it's own service model including aspects that are shared among OAPI specifications.
