### ISSUE TITLE
Coverage Offering

### ISSUE THREAD

**Issue by cmheazel** [opengeospatial/ogc_api_coverages#40]
The API-Coverages draft returns a Coverage Offering from /collections/{coverageid}/coverage. The schema for the resource this URL returns is mostly empty.  What should be included in a Coverage Offering?

**Comment by Schpidi** [comment]
Coverages SWG call: Lastest discussions and draft updates have resolved that issue (e.g. 6094940d8d2fed741f9bf7d40e548a7b372b58a3).
