### ISSUE TITLE
Scoping Parameters

### ISSUE THREAD

**Issue by cmheazel** [opengeospatial/ogc_api_coverages#41]
API-Coverages introduces the Range Set.  This is basically an n-dimensional collection of binary measurements. URL query parameters such as bbox or datetime do not work well here. The draft of API-Coverages attempts to provide a scope to query parameters. Has this effort been successful?  How could it be done better?

**Comment by pebau** [comment]
The range set component, as defined by the OGC CIS coverage standard, is just one way of modelling range values. It is not multi-dimensional (it does per se not know about dimensions),  but just a flat collection of values. Therefore, any function (such as subsetting) will not work on the range set as all these are defined on coverages. Rather, subsetting etc. must be provided on the /coverages/all path.

Subsetting has not been updated yet to reflect the latest changes. Earlier we thought for a moment that /coverage is the coverage but this idea has been discontinued, it just delivers metadata. Hence, applying subsetting to /coverages will not do the expected thing, rather /coverages/all now is "the coverage".

**Comment by pebau** [comment]
The range set component, as defined by the OGC CIS coverage standard, is just one way of modelling range values. It is not multi-dimensional (it does per se not know about dimensions),  but just a flat collection of values. Therefore, any function (such as subsetting) will not work on the range set as all these are defined on coverages. Rather, subsetting etc. must be provided on the /coverages/all path.

Subsetting has not been updated yet to reflect the latest changes. Earlier we thought for a moment that /coverage is the coverage but this idea has been discontinued, it just delivers metadata. Hence, applying subsetting to /coverages will not do the expected thing, rather /coverages/all now is "the coverage". 

PS: can someone please pint to the general format for describing query parameters, such as their scope (applicability) in a path? Thanks!

**Comment by cmheazel** [comment]
@pebau SWE Common allows you to store the values separate from the metadata which describes those values. The encoding of the stored values does not describe their structure, but that does not mean that they have no structure. In CIS that structure is defined by the Range Type and Domain Set. The Range Type and Domain Set are associated with the Range Set by being on the same */coverage path. Given the Domain Set and Range Type, both the client and the server have sufficient information to subset a Range Set.

**Comment by cmheazel** [comment]
@pebau OpenAPI provides a "parameter" object which can be used to define query parameters. Parameters can be defined anywhere on the path down to the HTTP operation. Once defined, the scope of a parameter is the current node and all sub-nodes. A parameter definition can override an existing definition, which allows us to limit depth of a parameters scope. A parameter can reside in the path, query, header, or cookie. 

I think this does most of what we need. However, OGC APIs do not mandate use of OpenAPI.  Do we have agreement that OpenAPI constructs can be used in normative text?  Should we add a description of the scope and behavior of a parameter to each level in the path?

**Comment by pebau** [comment]
OpenAPI is impressively powerful. A risk, though, is that in practice users may get lost: what's in the path, what in the cookie, etc.? Where in the path did I use what? Therefore, using the restriction capability makes much sense to me.

If we use OpenAPI normatively this likely makes the spec most immediate for OpenAPI usage, which seems an asset.

As to your 2nd question, to make the spec complete IMHO we cannot get around specifying all options for all path levels. As this could become painstaking for us it is a natural driver IMHO to restrict as much as possible. Not for prohibiting meaningful requests, but to rule out all that is not meaningful in a way easy to describe & grasp.

...my 2 fresh-in-the-year cents.

**Comment by pebau** [comment]
PS: re "In CIS that structure is defined by the Range Type and Domain Set." - This is just one possible representation of a coverage in CIS, we have more, such as coordinate/value pairs and sensor models (has been required _very_ strongly by various players, such as SWE folks). Hence, by restricting ourselves architecturally to domain/range set (such as tieing operations like subsetting to such components) we lose all the rest for OAPI.

**Comment by Schpidi** [comment]
Coverages SWG call: OBE - Overcome by events

**Comment by cmheazel** [comment]
Changes to the structure of the standards documents allow us to specify the scope of parameters - that is, which operations and target resources they apply to.
