### ISSUE TITLE
How to model resource (sub)selection based on the coverage model?

### ISSUE THREAD

**Issue by pebau** [opengeospatial/ogc_api_coverages#5]
Coverages are defined as having some canonical components, most importantly:
- domain set (where can I find values?)
- range set (what are the values?)
- range type (what does a value mean? - BTW, defined based on SWE Common so that the semantics is carried over to downstream services seamlessly)
- metadata (whatever else the coverage wants to tell us)

This could be translated natively into addressing like:
- /coverages/{id}/ -- give me the whole coverage
- /coverages/{id}/domainSet -- give me the domain set (ie, a description of where data siet, such as a bbox)
- /coverages/{id}/rangeSet -- give me the range set (ie, the pure pixel values, without any coordinates, metadata, etc.)
- /coverages/{id}/rangeType -- give me the semantics of the values, such as uom
- /coverages/{id}/metadata -- give me the coverage's metadata

**Comment by cmheazel** [comment]
@pebau This issue may be resolved by now.  Please review latest version (12/30/19 or latter) and let me know.

**Comment by pebau** [comment]
I concur, this can be closed. (We still should discuss "subsetting in core", but that's another issue.)
