### ISSUE TITLE
Renaming of WCS.SWG

### ISSUE THREAD

**Issue by pebau** [opengeospatial/ogc_api_coverages#69]
A motion has been initiated in the WCS.SWG to rename the SWG. This ticket serves to collect discussion and alternatives. Giving it a start:
- Alt 1: keep WCS.SWG -- issue: does not reflect OAPI sufficiently for some
- Alt 2: rename to OAPI-Coverages.SWG -- Issue: does not reflect WCS sufficiently for some
- Alt 3: have both in name, suggestions:
   - WCSOAPI.SWG
  - Web coverages - APIs and services SWG (James Passmore)
- pls add further suggestions + discussion below.

(this github place is maybe not appropriate for the discussion, but the [WCS.SWG charter change](https://github.com/opengeospatial/ogc_api_coverages/blob/master/charter/OGC-API-Coverages-SWG-Charter.adoc) has been put here, too, so why not have all together)

**Comment by pebau** [comment]
- Alt 4: Coverages.SWG -- Rationales: 
   - parallels Coverages.DWG
   - emphasizes the commonality (the data structure), rather than the variety (API techniques)

**Comment by ghobona** [comment]
The other alternative that has been suggested is:

* Alt 5: Establish OGC API - Coverages SWG as a separate working group from the WCS SWG

**Comment by chris-little** [comment]
Why does the name of the standard have to be the same as the name of the SWG?

Why not keep WCS SWG ( "it does what it says on the tin!") and call the API standard that it develops : OGC API - Coverages etc?

Maybe the real issue is whether the WCS SWG has enough human resources to do the OGC API - Coverages standard, and all of the collaboration, coordination and implementation that is required? Then this is an argument for a separate SWG. The WCS SWG then does the remaining stuff.

**Comment by cmheazel** [comment]
@pebau would the Coverages SWG be responsible for all coverage standards (including CIS)?  
@chris-little I see no reason why the name of the SWG must be the same as the standard.  Particularly in our case where the scope encompasses more than one standard.  However, I would hope that the name of the SWG is indicative of the scope of the SWG.  Question; what is the scope?

**Comment by ghobona** [comment]
Message from @Schpidi on 2020-07-01

"in today's WCS SWG meeting below motion was moved. The draft charter has been uploaded to pending (https://portal.ogc.org/files/?artifact_id=94093&version=1). The source of the PDF is available on GitHub from the link in the motion.

Motion: The WCS SWG recommends the draft charter (https://github.com/opengeospatial/ogc_api_coverages/blob/master/charter/OGC-Coverages-SWG-Charter.adoc) to the TC for a TC electronic vote
Moved: Stephan
Second: Peter
Discussion: Pending final edits
Result: Passed with NOTUC
"

**Comment by Schpidi** [comment]
The SWG has been officially rechartered as the "OGC Coverages SWG".
