### ISSUE TITLE
"scaling" conformance class

### ISSUE THREAD

**Issue by pomakis** [opengeospatial/ogc_api_coverages#78]
Has there been any discussion of a "scaling" conformance class to allow a client to request a coverage at a resolution other than the coverage's native resolution?

The WCS 2.0 Scaling Extension (OGC 12-039) defines the following parameters on the GetCoverage request: scaleFactor, scaleAxes, scaleSize, and scaleExtent.  CubeWerx's test OGC API implementation at https://test.cubewerx.com/cubewerx/cubeserv/demo/ogcapi/Daraa has implemented these parameters at the /collections/{collectionId}/coverage endpoint, and they work nicely.  So it should be a simple matter of adapting OGC 12-039 lock, stock and barrel as a conformance class of "OGC API - Coverages".

**Comment by chris-little** [comment]
@pomakis In the API EDR work, we had similar facilities, such as 'resolution' and some control over interpolation when retrieving data, but we postponed to a next version, to keep the current version simple. There were issues over how to specify some search terms consistently across different coordinate axes, such as horizontal (in metres) and vertical (in hectopascals) We decided to hide this from the end user client, as the server knows best.
I think 2D maps may not be such a great problem, but when we wrote the Met Ocean Application Profiles fro WCS, we allowed and encouraged interpolation to be forbidden, mainly for safety critical reasons. HTH.

**Comment by Schpidi** [comment]
Yes, a scaling conformance class is planned in a future part/extension (see https://github.com/opengeospatial/ogc_api_coverages/blob/master/extensions/overview.adoc)

**Comment by jerstlouis** [comment]
@Schpidi @pomakis I suggest that this should be in Part 1, but in its own conformance class, as it is essential functionality which all servers which can implement this should implement. Having it in its own conformance class would still allow server that cannot or really do not wish to implement it to still conform to the other coverage conformance classes.

For example, we discussed today how this is key functionality implemented by GDAL drivers, and tools built on GDAL rely heavily on this.

Downsampling / overviews is a very common need and encouraging servers to support it means not wasting bandwidth with full resolution when what clients really want is a downsampled overview. It also means a Tiles API can easily cut out the proper coverage tiles from a Coverages API to render them.

**Comment by Schpidi** [comment]
Coverages SWG call: The SWG agreed to include scaling as an additional conformance class to part 1. There was NOTUC.

@jerstlouis agreed to work on a first version including parameters `scaleFactor`, `scaleAxes`, and `scaleSize`.

**Comment by jerstlouis** [comment]
The scaling conformance class has been merged in, therefore I believe this issue can now be closed.

**Comment by Schpidi** [comment]
Merged scaling conformance class in #88
