### ISSUE TITLE
Coverage collections

### ISSUE THREAD

**Issue by nmtoken** [opengeospatial/ogc_api_coverages#8]
The benefits or not of building hierarchies, have possibly been done to death, but before we decide that we have a hierarchy that is `coverages/coverage,` how might we address a notion that a provider might want to create one or more sets of coverages ~ I know the idea has been proposed before (where a coverage could be a member of more than one set)?

**Comment by pebau** [comment]
BTW, a thought: the pattern emerging in OpenAPI Common, .../type/instance/... adds extra semantic burden on "/": before it was only aka hierarchical "drill-down", now it additionally connects types with instances. You might not see the structure in a URI anymore with all these zillions of slashes. What about spending an extra token for this type/instance relationship? Most names, should they be usable in XML world, are NCName, ie: names without a colon. Therefore, a colon might be the ideal separator:

http://www.acme.com/oapi/coverages:A/any:C

giving me "all coverages in set A with name C", which - in case of no ambiguity - could be abbreviated to 

http://www.acme.com/oapi/A/C

Similarly, requesting items of any type could be written as

http://www.acme.com/oapi/any:any

yielding features, coverages, documents, etc. I know, this begs a few more questions, but first of all wanted to share the basic idea of ".../type:instance/...".

**Comment by chris-little** [comment]
@pebau adding unusal syntax will not enamour the services to naive users or sophisticated developers. We are trying to make services available to a much wider audience, not geospatial or URL Syntax experts. Again, just because it is allowed by the syntax does not mean we should insist on it. It would constrain all the servers to process the colon. Also the XML world is, relatively, shrinking.

**Comment by dblodgett-usgs** [comment]
Hi All, I'm having a very hard time following this thread. Can someone please clean up the email-artifacts in @pebau's responses above and summarize the conversation and logic for using `https://acme.com/collections/{collectionId}/coverage/{coverageId}`. 

In OGC-API Features, "collections" is really meant to be "feature-collections". Does "collections" here mean "coverage-collections"? Would it be the worst thing to use `https://acme.com/collections/{collectionId}/items/{coverageId}` to be more consistent with OGC-API Features?

**Comment by Schpidi** [comment]
20191204 Teleconference: At the Toulouse TC meeting is was decided to use only the `/coverage` path and drop `/coverages`. This means there is a one-to-one relation between collection and coverage. Hierarchies are discussed to be added in a generic way for the whole OGC APIs.

**Comment by cmheazel** [comment]
Re-opened at the request of participants of the ESIP Sprint.

**Comment by Schpidi** [comment]
20200513 Teleconference: @cmheazel could you maybe elaborate a bit on why this issue was reopened? Otherwise we would consider re-closing it. Thanks

**Comment by chris-little** [comment]
@Schpidi There may be a different answer from @cmheazel , but I suggest that it is a good place to review and confirm the relationship of coverages and OGC API - Common, Part 1: Core, as Collections are now Part 2

**Comment by Schpidi** [comment]
WCS SWG teleconference decided to close again.

**Comment by dblodgett-usgs** [comment]
@Schpidi do you feel that the WCS SWG perspective is adequately represented in the OAPI Common discussion?

**Comment by pebau** [comment]
@dblodgett-usgs great that you ask - allow me to answer although I am not addressed personally: my observation throughout the OAPI discussions is that OAPI is dominated by Features, and more than once coverage considerations got sidelined. 
One (although maybe not the central) example is the collection issue: at the OGC/ESIP spring in January several decade-experienced coverage experts from both sides of the Atlantic have motivated the need for coverage collections, still they get disregarded. Another one is the "coverage = collection" equation that dominates design, leading to sometimes counter-intuitive and technically problematic coverage API constructs.
More than once I heard "but we cannot change this, OAPI-Features has brought this in and there it is frozen already".

**Comment by ghobona** [comment]
@dblodgett-usgs @pebau This issue was discussed during the SWG call today and there was no objection raised to closing the issue, for the reason stated in https://github.com/opengeospatial/ogc_api_coverages/issues/8#issuecomment-631504778.

**Comment by dblodgett-usgs** [comment]
@ghobona -- I appreciate that. Just trying to provoke some engagement in the API-Common discussion.

@pebau -- you did not answer my question. As the discussion about collections progresses, I want to be sure that someone with knowledge of the nuances of current state of API-Coverages is taking part in the conversation about API-Common. 

Regarding the rest of your response, your recollection aligns with mine but the book is not completely written. The issues are larger than features and coverages and it may come to pass the `/collections` literal API path is restricted to feature collections and, **for instance**, coverages would introduce a `/coverages` root path that would contain items that are of type `Coverage` and have behavior described in API-coverages conformance classes.

**Comment by Schpidi** [comment]
@dblodgett-usgs I'd hope the coverages perspective is well represented in common but I guess it could be better. I'll keep asking in the coverages group for volunteers to join the discussions as it is quite difficult to find enough time for me personally.

**Comment by dblodgett-usgs** [comment]
Thanks @Schpidi -- the key is that it's not _just_ perspective, but knowledge of the nuances and an eye on how the overall system of APIs will work together. Please to encourage active participation.

**Comment by pebau** [comment]
@dblodgett-usgs, all: IMHO the key issue is that concepts are mixed up - a collection is a standalone mechanism, useful all over the place (which recent discussion shows dramatically). A coverage in the first place is a coverage, not a collection. Rather different mechanics. Would we accept it we could get the coverage collections that some requested, and more. And the difficulties discussed could be disentangled better.

**Comment by dblodgett-usgs** [comment]
@pebau -- do you have a problem with this text?

> API-Coverages observes that a coverage is a collection of measured values. Therefore, a coverage is a collection.

Found that in the draft API Coverages spec: http://docs.opengeospatial.org/DRAFTS/19-087.html#collection-access-section

In getting to what seems to be consensus in https://github.com/opengeospatial/oapi_common/issues/140#issuecomment-637664012 I found that much if not all of the issue we were addressing was a failure to clearly communicate concepts and intentions. 

A particularly valuable detail is Proposed Solution 2:

> The definition of Collection needs to be less obtuse and more evocative for developers.
> 
> Current def from [20-024](http://docs.opengeospatial.org/DRAFTS/20-024.html#terms_and_definitions)
> 
> A body of resources that belong or are used together. An aggregate, set, or group of related resources. (OGC 20-024)
> 
> I think what we are saying here is that a (OGC-API) Collection is:
> "A geospatial data resource that may be available as one or more sub-resource distributions that conform to one or more OGC API standards."
> 
> Some statements we can say about an OGC-API Collection:
> 
> 1. A collection may have spatial-temporal extent.
> 1. A collection has one or more representations/distributions available as OGC APIs.
> 1. If available as items, the collection will implement items consistently.

In a sense, a coverage is a representation of a collection -- just as a feature-collection is.

**Comment by chris-little** [comment]
@pebau I like this. This is consistent with the EDR API too. We have deliberately avoided using the terms 'Feature' and 'Coverage' in the documents, but the EDR API does query against a single coverage, which is usually 4-D. And we have implemented EDR API over a WCS service.

We will clarify that this is the EDR API approach to 'Collection'.

**Comment by jerstlouis** [comment]
To get back to some wishing for "collections of Coverages", I completely understand this,
but a Collection of coverages, is much akin to a Collection of "feature collections", and for the problem to be solved consistently, it calls for hierarchical collections, which may have to be an extension (discussed in https://github.com/opengeospatial/oapi_common/issues/11).

**Comment by dblodgett-usgs** [comment]
Over in EDR -- we are taking a somewhat different tack that might get the same place. Since an EDR resource may have multiple versions or ensemble members, etc. we have introduced an `{instanceID}` mechanism that allows you to access one of _n_ instances of the EDR resource. Maybe a similar pattern could be adopted here? I see no reason that instances couldn't themselves have instances to get the hierarchy.

**Comment by pebau** [comment]
@jerstlouis 
> a Collection of coverages, is much akin to a Collection of "feature collections", and for the problem to be solved consistently, it calls for hierarchical collections

yes, +100!!! That was also a strong recommendation of a substantial set of stakeholders at the OGC/ESIP coverage analytics sprint in January.

**Comment by pebau** [comment]
@dblodgett-usgs just cleaning up my stack, apologies if it is already obsolete.

> @pebau -- do you have a problem with this text?
> > API-Coverages observes that a coverage is a collection of measured values. Therefore, a coverage is a collection.

yes - I always was against this. First, because it is misleading (a coverage is not just a collection), second because this definition trusted that a stable definition of collection would come, which still is not there.

> > "A geospatial data resource that may be available as one or more sub-resource distributions that conform to one or more OGC API standards."

"may be"...what if not? what is a distribution? what OGC standards - we have abstract specs, concepts, data structures,  encodings, services of a wide variety.

> > Some statements we can say about an OGC-API Collection:
> > 
> > 1. A collection may have spatial-temporal extent.

again, "may" - so what does it help if we say may or may not have an extent?

> > 2. A collection has one or more representations/distributions available as OGC APIs.

hm, "as API" -> "via API" ? how does this contribute to the definition that a client programmer reads? What it firmly states, though, is that a ciollection can never be empty.

what is "representation referring to, representation of what? "distribution? "/" = "or", so a mix?

> > 3. If available as items, the collection will implement items consistently.

how does a collection implement something? does it say "conforms to all rules defined on items"? And what if not?

...so altogether, I find this more confusing than explaining.

> In a sense, a coverage is a representation of a collection -- just as a feature-collection is.

no. A coverage is a function in the first place. This function can be represented in various ways, one (!) of which is as a feature collection, but with additional constraints and data items. Such as in a grid coverage: the "feature" coordinates must sit on a grid defined in  the coverage.

**Comment by dblodgett-usgs** [comment]
Hi @pebau -- going to try and contain my frustration with how this debate has gone so pardon any  that leaks into my response -- it is not targeted at you.

re: the relationship of the conceptual definition of coverages and collections,  

I was assuming (wrongly) that the text in the draft Coverages API spec was agreed to. It is too bad that you were overruled and no consensus could be found on the relationship of a coverage to a collection. Perhaps we reword to reflect that, "_a coverage is a distribution of a collection of geospatial data._"?

re: the "may" terminology,

I agree that is unfortunate, however they are necessary to allow collectionInfo with no distributions available to the client (e.g. permissions limits or some other business rules) and to allow inclusion of non-geospatial data as is already allowed in Features core. I think these are both points that we could and probably should debate further but the statements do reflect the status quo of the debate.

Re: distribution / representation

I would refer you to the [W3C DCAT definition of distribution.](https://www.w3.org/TR/vocab-dcat-2/#Class:Distribution) which starts: "Distribution: A specific representation of a dataset." What we are saying with that statement is that a /collections/{collectionid} resource is an abstract dataset that is distributed by OGC API representations. That is all -- if you are looking for more specifics, we have work to do still. I hope you can join the conversation as we work through the details.

Excuse me for being imprecise with my description of a coverage being a representation of a collection, I was assuming you would be more charitable in your interpretation of my phrasing.

Collections could be coverages or features you don't know until you've discovered that `/collections/{collectionid}/coverage` is a link item (with rel: coverage) in the collectioninfo document returned from the `/collections/{collectionid}` resource. So in that sense, a `/collections/{collectionid}/coverage` resource is a representation of a `/collections/{collectionid}` resource which its self (on the server, unavailable to a client directly) could be a mathematical coverage, a cell coverage, a feature coverage, a point cloud, or any other data that can be represented and distributed through a coverages API.

Are we getting somewhere? I think that if, at the end of the day, you can agree that it is a good idea to use the basic notion that @jerstlouis has been advocating for, `/collections/{collectionid}` resources can be represented as either items or other distributions, then we can move forward debating the details and refining our approach. If not, then we need to stop debating these details and look at a much higher level of the architecture than is being discussed here.

**Comment by pebau** [comment]
@dblodgett-usgs - sorry to hear about your frustration; indeed, a long and winding road! 
"Distribution" first rings a mathematical bell with me, not sure why we need yet another term? In particular, as it is as ill defined as ever: specific = ? representation = ? dataset = ?

I keep on wondering why we so much refuse to establish concise definitions that are low-hanging fruits as they are used all over the place everywhere, and rather invent counterintuitive terms.

Normally we would have an ordered approach modeling information structures, APIs, rather than juggling paths with fuzzy, uncodified descriptions. Sorry, not at all pointing at you, but at the whole unguided process consequently ignoring industry best practices.

Yes, frustrated, too. One reason for be to stay silent for long, although I have tried to overcome this for a few days now ;-)
.

**Comment by chris-little** [comment]
@pebau We are not " ignoring industry best practices". But these Best Practices come from the W3C not OGC, and we are trying to create OGC (Web) APIs, so we are adhering to [W3C's  Spatial Data on the Web BPs](https://www.w3.org/TR/sdw-bp/)

As the Web is loosely coupled (not necessarily a weakness) so are the resource orientated views of things. We may not be able to do 'a priori' modelling or have an ordered approach.

And if we wish to make use of Linked Data, we have to get used to 'distributions'.
