### ISSUE TITLE
Scaling, Subsetting "beyond" the coverage (BBOX + resolution interoperability), and slicing irregular coverages

### ISSUE THREAD

**Issue by jerstlouis** [opengeospatial/ogc_api_coverages#84]
We would like to support a common simple mechanism to sub-set geospatial data across the OGC API standards family (e.g. the semantics of which, but not the result, would be defined in _OGC API - Common - Part 2: Geospatial data_).

This allows for example to easily cut coverage tiles with BBOX (potentially CRS84h including vertical elevation), width, height and dateTime parameters.

Recent attempts to do this with WCS and WCPS are showing that this is surprisingly difficult to achieve:
- It is not clear whether WCPS is required or this can be done with simply `scaleFactor` and `subset` parameters
- Using WCPS:
   - `scale()` is not necessarily implemented with n-D pyramids and thus may process too much data unnecessarily
   - `extend()` must be used to try to subset beyond the coverage's domainset before scaling, which may result in generating too much data unnecessarily
   - irregular coverages have limitations regarding slicing

A valid concern would be is that for the same reason this is difficult to achieve with WCS, it may be difficult to implement this functionality as a facade on top of WCS, so perhaps this could live in conformance classes that not all implementations would implement initially.

**Comment by Schpidi** [comment]
20200902: Coverages SWG call: It was decided to not use `/` as delimiter for various reasons like not being usable in paths although ISO8601 and WMS would use `/` for intervals. The proposal for the subset parameter on the table is:  `&subset=Lat(30:42),Long(-125:-115),Time("2020-08-11T12:32:00Z":"2020-08-11T14:47:00Z")`. i.e. to have a single `subset` parameter and use `:` as delimiter per axis and `,` as delimiter between axes. This is also discussed in https://github.com/opengeospatial/oapi_common/issues/167 as proposal to make this part of common.

**Comment by Schpidi** [comment]
20200909: Coverages SWG call: NOTUC to adopt the proposal and merge #88 once extended to fully reflect the proposal.

Please open a separate issue if an individual aspect of this one isn't covered yet.
