### ISSUE TITLE
Subsetting (partially) outside the coverage's extent

### ISSUE THREAD

**Issue by Schpidi** [opengeospatial/ogc_api_coverages#86]
20200902: Coverages SWG call:

Factoring out from https://github.com/opengeospatial/ogc_api_coverages/issues/84

Use case: Fill a GeoPackage from Coverages API with coverage tiles

Proposal: Allow subsetting outside of the extent/domainSet of a coverage and document the options, potentially make a recommendation but don't mandate one or the other.

Options are:
* Recommended: Fill the extent with no-data values at least for partially outside requests
* Respond with an http error 501 "Not implemented"
* Not recommended: Respond with a subset that is smaller than the requested one

**Comment by jerstlouis** [comment]
This partly addresses https://github.com/opengeospatial/ogc_api_coverages/issues/27 (although a Tiles API may also be another mechanism).

**Comment by Schpidi** [comment]
20200907: Coverages SWG call: Decided to relax the requirement of WCS 2 that the min and max values used with the subset parameter have to be contained within the axis range defined in the domainSet. A partially outside subset should be filled with no-data values whereas a fully outside subset should return with http status code 204 (cf. https://github.com/opengeospatial/OGC-API-Tiles/issues/21).

**Comment by jerstlouis** [comment]
I believe the changes have been applied and merged and this issue can now be closed.

**Comment by Schpidi** [comment]
Coverages SWG call: Agreed to close.
