### ISSUE TITLE
Subsetting by range type (bands)

### ISSUE THREAD

**Issue by jerstlouis** [opengeospatial/ogc_api_coverages#99]
The Scope clause (1) was recently updated to include subsetting by range type in _Part 1: Core_.

I don't believe there is yet a conformance class defined for this -- it needs to be added.

Would this be done via `?rangeSubset=rain,tmin,tmax` as originally discussed in #25 ?
Should it be considered to align this with `properties=` in Features?

**Comment by Schpidi** [comment]
Closing as PR was merged.
